{{- if .Values.serviceAccountCreate -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: drain-node-on-crash
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: drain-node-on-crash
  labels:
    app: drain-node-on-crash
rules:
- apiGroups:
  - '*'
  resources:
    - '*'
  verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drain-node-on-crash
  labels:
    app: drain-node-on-crash  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drain-node-on-crash
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.Namespace }}
{{- end -}}
